export default nodeListRecords = [
  {
    id: 1,
    imageColor: "#3e3a39",
    name: "Active Branch",
    tag: "Control",
  },
  {
    id: 2,
    imageColor: "#c72128",
    name: "Binner",
    tag: "Binning",
  },
  {
    id: 3,
    imageColor: "#37b44b",
    name: "CSV Reader",
    tag: "Streamable",
  },
  {
    id: 4,
    imageColor: "#1e6da8",
    name: "Denormalizer",
    tag: "Column",
  },
  {
    id: 5,
    imageColor: "#ff9632",
    name: "Extract Color",
    tag: "Views",
  },
  {
    id: 6,
    imageColor: "#d30d52",
    name: "File Reader",
    tag: "Read",
  },
  {
    id: 7,
    imageColor: "#c72128",
    name: "GroupBy",
    tag: "Transform",
  },
  {
    id: 8,
    imageColor: "#37b44b",
    name: "Histogram",
    tag: "Views",
  },
  {
    id: 9,
    imageColor: "#1e6da8",
    name: "IF Switch",
    tag: "Switches",
  },
  {
    id: 10,
    imageColor: "#ff9632",
    name: "Joiner",
    tag: "Manipulation",
  },
  {
    id: 11,
    imageColor: "#d30d52",
    name: "KNIME Connector",
    tag: "Connectors",
  },
  {
    id: 12,
    imageColor: "#3e3a39",
    name: "Line Reader",
    tag: "Streamable",
  },
  {
    id: 13,
    imageColor: "#c72128",
    name: "MDS",
    tag: "Mining",
  },
  {
    id: 14,
    imageColor: "#37b44b",
    name: "Normalizer",
    tag: "Column",
  },
  {
    id: 15,
    imageColor: "#1e6da8",
    name: "One to Many",
    tag: "Transform",
  },
  {
    id: 16,
    imageColor: "#ff9632",
    name: "PCA",
    tag: "Analytics",
  },
  {
    id: 17,
    imageColor: "#d30d52",
    name: "Rank",
    tag: "Row",
  },
  {
    id: 18,
    imageColor: "#3e3a39",
    name: "SQl Inject",
    tag: "Database",
  },
  {
    id: 19,
    imageColor: "#c72128",
    name: "Table Creater",
    tag: "IO",
  },
  {
    id: 20,
    imageColor: "#37b44b",
    name: "Ungroup",
    tag: "Streamable",
  },
  {
    id: 21,
    imageColor: "#1e6da8",
    name: "Variable Creater",
    tag: "Loop Support",
  },
  {
    id: 22,
    imageColor: "#ff9632",
    name: "Wait",
    tag: "Automation",
  },
  {
    id: 23,
    imageColor: "#d30d52",
    name: "XML to PMML",
    tag: "PMML",
  },
];
