const nodeListRecords = [
  {
    id: 1,
    imageColor: "#3e3a39",
    name: "Active Branch",
    short_name:'AB',
    tag: "Control",
  },
  {
    id: 2,
    imageColor: "#c72128",
    name: "Binner",
    short_name:'BI',
    tag: "Binning",
  },
  {
    id: 3,
    imageColor: "#37b44b",
    name: "CSV Reader",
    short_name:'CR',
    tag: "Streamable",
  },
  {
    id: 4,
    imageColor: "#1e6da8",
    name: "Denormalizer",
    short_name:'DN',
    tag: "Column",
  },
  {
    id: 5,
    imageColor: "#ff9632",
    name: "Extract Color",
    short_name:'EC',
    tag: "Views",
  },
  {
    id: 6,
    imageColor: "#d30d52",
    name: "File Reader",
    short_name:'FR',
    tag: "Read",
  },
  {
    id: 7,
    imageColor: "#c72128",
    name: "GroupBy",
    short_name:'GB',
    tag: "Transform",
  },
  {
    id: 8,
    imageColor: "#37b44b",
    name: "Histogram",
    short_name:'HG',
    tag: "Views",
  },
  {
    id: 9,
    imageColor: "#1e6da8",
    name: "IF Switch",
    short_name:'IS',
    tag: "Switches",
  },
  {
    id: 10,
    imageColor: "#ff9632",
    name: "Joiner",
    short_name:'JO',
    tag: "Manipulation",
  },
  {
    id: 11,
    imageColor: "#d30d52",
    name: "KNIME Connector",
    short_name:'KC',
    tag: "Connectors",
  },
  {
    id: 12,
    imageColor: "#3e3a39",
    name: "Line Reader",
    short_name:'LR',
    tag: "Streamable",
  },
  {
    id: 13,
    imageColor: "#c72128",
    name: "MDS",
    short_name:'MD',
    tag: "Mining",
  },
  {
    id: 14,
    imageColor: "#37b44b",
    name: "Normalizer",
    short_name:'NZ',
    tag: "Column",
  },
  {
    id: 15,
    imageColor: "#1e6da8",
    name: "One to Many",
    short_name:'OM',
    tag: "Transform",
  },
  {
    id: 16,
    imageColor: "#ff9632",
    name: "PCA",
    short_name:'PC',
    tag: "Analytics",
  },
  {
    id: 17,
    imageColor: "#d30d52",
    name: "Rank",
    short_name:'RK',
    tag: "Row",
  },
  {
    id: 18,
    imageColor: "#3e3a39",
    name: "SQl Inject",
    short_name:'SI',
    tag: "Database",
  },
  {
    id: 19,
    imageColor: "#c72128",
    name: "Table Creater",
    short_name:'TC',
    tag: "IO",
  },
  {
    id: 20,
    imageColor: "#37b44b",
    name: "Ungroup",
    short_name:'UG',
    tag: "Streamable",
  },
  {
    id: 21,
    imageColor: "#1e6da8",
    name: "Variable Creater",
    short_name:'VC',
    tag: "Loop Support",
  },
  {
    id: 22,
    imageColor: "#ff9632",
    name: "Wait",
    short_name:'WT',
    tag: "Automation",
  },
  {
    id: 23,
    imageColor: "#d30d52",
    name: "XML to PMML",
    short_name:'XP',
    tag: "PMML",
  },
];

export default nodeListRecords;
